#!/usr/bin/env python3
"""Generate Step60 B≡14 lists from named Step60 rows.

Extracts unique `def row_B_C` with B ≡ 14 (mod 16) from the
Step60 capstone, computes the displayed Frey trace
a53(E_B) = -∑ χ(x(x-B⁴)(x+C⁴)) on F_53, and writes:

  Step60B14List.lean  — 352 numerals
  B14Witnesses.lean   — (B, 53, a53) triples

This is a coefficient record, not Ribet and not a
Beal negation.  density_5983_list stays
[196, 1500003] (neither is ≡ 14).

  python3 scripts/gen_b14_kraus.py
  python3 scripts/gen_b14_kraus.py --dump-b14 --format lean
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STEP60 = (
    ROOT
    / "lean/BealLevel26Foundations/Beal/FullProof"
    / "Beal_4_13_13_Zsigmondy_13_Step60_B_le_2000k_299.lean"
)
OUT_WIT = (
    ROOT
    / "lean/BealLevel26Foundations/Beal/FullProof/B14Witnesses.lean"
)
OUT_LIST = (
    ROOT
    / "lean/BealLevel26Foundations/Beal/FullProof/Step60B14List.lean"
)


def euler_chi(a: int, p: int) -> int:
    if a % p == 0:
        return 0
    e = pow(a, (p - 1) // 2, p)
    return 1 if e == 1 else -1


def a53_E(B: int, C: int) -> int:
    p = 53
    b4 = pow(B, 4, p)
    c4 = pow(C, 4, p)
    s = 0
    for x in range(p):
        f = (x * ((x - b4) % p) * ((x + c4) % p)) % p
        s += euler_chi(f, p)
    return -s


def collect_pairs() -> list[tuple[int, int]]:
    text = STEP60.read_text()
    rows = [
        (int(b), int(c))
        for b, c in re.findall(r"^def row_(\d+)_(\d+)", text, re.M)
    ]
    seen: set[int] = set()
    pairs: list[tuple[int, int]] = []
    for B, C in rows:
        if B % 16 != 14 or B in seen:
            continue
        if C != B + 3:
            raise SystemExit(f"C != B+3 for {B},{C}")
        seen.add(B)
        pairs.append((B, a53_E(B, C)))
    vals = Counter(a for _, a in pairs)
    for a in vals:
        if a % 13 in (0 % 13, 12 % 13):
            raise SystemExit(f"a53={a} does not miss 0/12")
    return pairs


def write_list(pairs: list[tuple[int, int]]) -> None:
    lines = [
        "/-",
        "Copyright (c) 2026 David Fox. All rights reserved.",
        "Released under MIT license as described in the file LICENSE.",
        "Authors: David Fox",
        "",
        "Named Step60 rows with B ≡ 14 (mod 16).",
        "352 numerals, same order as b14_witnesses.",
        "Not a 5983-numeral dump.  Not Ribet.  Not ¬∃ A.",
        "Generated by scripts/gen_b14_kraus.py.",
        "-/",
        "",
        "namespace BealLevel26Foundations.Step60B14List",
        "",
        "/-- Named Step60 `B` with `B % 16 = 14`. -/",
        "def step60_b14_list : List Nat :=",
        "  [",
    ]
    for i, (B, _) in enumerate(pairs):
        comma = "," if i + 1 < len(pairs) else ""
        lines.append(f"    {B}{comma}")
    lines += [
        "  ]",
        "",
        "set_option maxRecDepth 4096",
        "",
        "theorem step60_b14_list_length : step60_b14_list.length = 352 := by",
        "  decide",
        "",
        "end BealLevel26Foundations.Step60B14List",
        "",
    ]
    OUT_LIST.write_text("\n".join(lines))


def write_witnesses(pairs: list[tuple[int, int]]) -> None:
    lines = [
        "/-",
        "Copyright (c) 2026 David Fox. All rights reserved.",
        "Released under MIT license as described in the file LICENSE.",
        "Authors: David Fox",
        "",
        "Displayed (B, 53, a53) triples for the 352 named",
        "Step60 rows with B ≡ 14 (mod 16).",
        "a53 is the Euler point-count of",
        "y² = x(x − B⁴)(x + (B+3)⁴) over F_53.",
        "Not a theorem that this equals the Beal",
        "Frey curve.  Not Ribet.  Not ¬∃ A.",
        "Generated by scripts/gen_b14_kraus.py.",
        "-/",
        "",
        "namespace BealLevel26Foundations.B14Witnesses",
        "",
        "/-- Named Step60 rows with `B % 16 = 14`,",
        "paired with Kraus prime `53` and the",
        "displayed `a₅₃` integer. -/",
        "def b14_witnesses : List (Nat × Nat × Int) :=",
        "  [",
    ]
    for i, (B, a) in enumerate(pairs):
        comma = "," if i + 1 < len(pairs) else ""
        lines.append(f"    ({B}, 53, {a}){comma}")
    lines += [
        "  ]",
        "",
        "set_option maxRecDepth 4096",
        "",
        "theorem b14_witnesses_length : b14_witnesses.length = 352 := by",
        "  decide",
        "",
        "end BealLevel26Foundations.B14Witnesses",
        "",
    ]
    OUT_WIT.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dump-b14",
        action="store_true",
        help="Write Step60B14List.lean and B14Witnesses.lean",
    )
    parser.add_argument(
        "--format",
        choices=["lean"],
        default="lean",
        help="Output format (lean)",
    )
    parser.parse_args()
    pairs = collect_pairs()
    vals = Counter(a for _, a in pairs)
    write_list(pairs)
    write_witnesses(pairs)
    print(
        f"wrote {OUT_LIST.name} and {OUT_WIT.name} "
        f"n={len(pairs)} a53={dict(vals)}"
    )


if __name__ == "__main__":
    main()
