/-
  Galois/07h_OldNewOnV — old/new boundary on genuine-form generators

  This layer specifies what it means, without lattice closure, for a supplied
  Hecke-stable submodule to be generated by the finite genuine-form boundary.
  It also exposes the missing old/new complement input and performs the valid
  conditional transport from restricted Ihara kernel-zero to the existing
  V-specific decomposition hypothesis.

  No old/new decomposition is constructed here.  In particular, the finite
  coefficient model does not supply an Atkin–Lehner projector, the
  localization, quotient, or geometric newform theorem needed to inhabit the
  explicit `AtkinLehnerProjectorOnV` premise.
-/
import Beal.Galois.«07g_IharaOnV»
import Beal.Galois.«07d_OldNew»

namespace Beal.Galois

/-- A constructively stated replacement for “the span of genuine forms”.

    `V` is Hecke-stable, contains every finite genuine-form sequence, and is
    contained in every other Hecke-stable submodule with that property.  This
    avoids `Submodule.span`, whose lattice implementation adds
    `Classical.choice` to the Lean 4.12 axiom audit. -/
def IsGenuineFormGeneratedAtLevel (M ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ)) : Prop :=
  IsModularFormAtLevel M ℓ V ∧
    (∀ f : CoefficientSequence ℓ,
      IsGenuineModularFormAtLevel M ℓ f → f ∈ V) ∧
      ∀ W : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
        IsModularFormAtLevel M ℓ W →
          (∀ f : CoefficientSequence ℓ,
            IsGenuineModularFormAtLevel M ℓ f → f ∈ W) →
              ∀ v : CoefficientSequence ℓ, v ∈ V → v ∈ W

/-- The V-specific old/new hypothesis consumed by the support assembly.

    This definition used to live in 07j, but it belongs at this boundary:
    07j imports 07h and therefore cannot be imported back into 07h without a
    cycle.  Its proposition shape is unchanged.  The first conjunct records
    that `V` is the genuine-form-generated module; the second supplies
    Hecke-stable old and new submodules with an internal direct-sum witness. -/
def OldNewDecompHyp
    {M ℓ : ℕ}
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ)) : Prop :=
  IsGenuineFormGeneratedAtLevel M ℓ V ∧
    ∃ Old New : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
      IsModularFormAtLevel M ℓ Old ∧
        IsModularFormAtLevel M ℓ New ∧
          IsInternalDirectSum V Old New

/-- Explicit old/new complement input for a genuine level-`M` submodule.

    The finite coefficient model provides neither the geometric old subspace
    nor its new complement.  This proposition records exactly the missing
    implication needed by the conditional theorem below: once restricted
    Ihara kernel-zero is supplied, the actual old/new construction must return
    a genuine-form-generated module and an internal direct-sum decomposition.

    The name refers to the classical Atkin–Lehner/complement input, not to a
    Lean construction of an Atkin–Lehner operator.  No Petersson product,
    projector, localization, or newform theorem is hidden in this definition. -/
def AtkinLehnerProjectorOnV (M p ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ)) : Prop :=
  IsGenuineFormGeneratedAtLevel M ℓ V ∧
    (IharaKernelZeroOnV M p ℓ V →
      ∃ Old New : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
        IsModularFormAtLevel M ℓ Old ∧
          IsModularFormAtLevel M ℓ New ∧
            IsInternalDirectSum V Old New)

/-- Conditional old/new transport from restricted Ihara kernel-zero.

    This theorem does not identify `Old` with a degeneracy-map image by
    itself.  That identification and the complement construction are the
    explicit `AtkinLehnerProjectorOnV` premise. -/
theorem old_new_decomp_from_ihara
    (M p ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ))
    (hIhara : IharaKernelZeroOnV M p ℓ V)
    (hProjector : AtkinLehnerProjectorOnV M p ℓ V) :
    OldNewDecompHyp (M := M) (ℓ := ℓ) V := by
  rcases hProjector with ⟨hGenerated, hComplement⟩
  rcases hComplement hIhara with ⟨Old, New, hOld, hNew, hSum⟩
  exact ⟨hGenerated, Old, New, hOld, hNew, hSum⟩

/-- Conditional old/new transport from the genuine-form and q-expansion
    premises.

    The 07g theorem supplies restricted Ihara kernel-zero.  The remaining
    old/new complement premise stays explicit and is not proved here. -/
theorem old_new_decomp_from_genuine
    (M p ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ))
    (hV : IsGenuineFormSubmoduleAtLevel M ℓ V)
     (qExpansion : QExpansionPrincipleOnV M p ℓ V)
    (hProjector : AtkinLehnerProjectorOnV M p ℓ V) :
    OldNewDecompHyp (M := M) (ℓ := ℓ) V := by
  apply old_new_decomp_from_ihara M p ℓ V
     (ihara_zero_on_genuine_V_conditional M p ℓ V hV qExpansion)
  exact hProjector

/-- Conditional V-specific old/new decomposition.

    `OldNewDecompHyp` is an explicit proposition parameter, not a locally
    defined replacement theorem.  A future proof must inhabit it using the
    actual finite modular-form, localization, and quotient input. -/
theorem genuineFormGenerated_oldNew_of_hyp
    {M p ℓ : ℕ}
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ))
    (hGenerated : IsGenuineFormGeneratedAtLevel M ℓ V)
    (OldNewDecompHyp : Prop)
    (hOldNew :
      OldNewDecompHyp →
        p.Prime ∧
          ∃ Old New : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
            IsModularFormAtLevel M ℓ Old ∧
              IsModularFormAtLevel M ℓ New ∧
                IsInternalDirectSum V Old New)
    (hHyp : OldNewDecompHyp) :
    p.Prime ∧
      ∃ Old New : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
        IsModularFormAtLevel M ℓ V ∧
          IsModularFormAtLevel M ℓ Old ∧
            IsModularFormAtLevel M ℓ New ∧
              IsInternalDirectSum V Old New := by
  rcases hOldNew hHyp with ⟨hp, Old, New, hOld, hNew, hSum⟩
  exact ⟨hp, Old, New, hGenerated.1, hOld, hNew, hSum⟩

-- MISSING: inhabit `OldNewDecompHyp` with the actual old/new decomposition
-- for the finite genuine-form-generated Hecke module.

#print axioms IsGenuineFormGeneratedAtLevel
#print axioms OldNewDecompHyp
#print axioms AtkinLehnerProjectorOnV
#print axioms old_new_decomp_from_ihara
#print axioms old_new_decomp_from_genuine
#print axioms genuineFormGenerated_oldNew_of_hyp
-- Expected foundational dependencies: [propext, Quot.sound] only.

end Beal.Galois