/-
Copyright (c) 2026 David Fox. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Fox
-/
import TateCurve.BlockerDoc

/-!
# Continued Tate-closure boundary at baseline `43735b3`

This module keeps the next local argument in its valid forward order:

1. construct a curve-attached `q : ℚ_29` with positive valuation;
2. construct the convergent full series
   `j(q) = q⁻¹ + 744 + 196884q + q² R(q)` and invert it on the open unit disc;
3. equip `ℚ_29ˣ / q^ℤ` with its Tate elliptic-curve structure and prove the
   exact two `j`-equalities identifying it with the Frey base change;
4. use the resulting uniformization certificate to run Tate's algorithm,
   obtain Kodaira type `I_(26k)`, and identify the Néron conductor with the
   displayed `32`/`928` split;
5. construct the geometric mod-`13` representation and prove the cyclotomic
   inertia formula through the extension generated by `q^(1/13)`; and
6. deduce the required unramifiedness only in this forward direction.

The finite expression `tateJTruncation` is not the full series.  The quotient
`TateMultiplicativeQuotient` is only a group quotient until the analytic
functions and Weierstrass model are constructed.  The numerical equalities
proved below do not inhabit `TateClosureContinued`.
-/

namespace BealMatveevBeal.TateCurve

open BealMatveevBeal.DarmonMerelFrey4413
open BealMatveevBeal.Tate_I29_Inertia
open BealMatveevBeal.Tate_Frey_Conductor_29_Numerical

/-- The full-series interface exposes its remainder term; this is the exact
contract needed before any inversion argument can begin. -/
theorem full_tate_j_series_with_remainder {K : Type*} [Field K]
    (series : FullTateJSeries K) (q : K) (hq : q ≠ 0) :
    series.j q = tateJTruncation q + q ^ 2 * series.remainder q :=
  series.expansion q hq

/-- A uniformization certificate contains both exact `j`-equalities.
This projection is forward only and does not manufacture the certificate. -/
theorem uniformization_certificate_exact_j_equalities {A B : ℕ}
    {hsol : A ^ 4 + B ^ 4 = (B + 3) ^ 13}
    (data : TateUniformizationData A B hsol) :
    data.tateCurve.j = data.jSeries.j data.parameter.q ∧
      data.freyBaseChange.j = data.jSeries.j data.parameter.q :=
  ⟨data.j_tate_eq_series, data.frey_j_eq_series⟩

/-- The complete next boundary.  Every conjunct is an existing construction
obligation.  No numerical identity is used backwards to inhabit it. -/
def TateClosureContinued : Prop :=
  Tate_uniformization ∧
    Frey_conductor_29_is_Neron ∧
    Tate_cyclotomic_inertia_formula ∧
    inertia_at_29_trivial_mod13_full

/-- A completed closure would project to the existing uniformization,
Néron-conductor, cyclotomic-inertia, and unramifiedness boundaries. -/
theorem tate_closure_continued_forward (h : TateClosureContinued) :
    Tate_uniformization ∧
      Frey_conductor_29_is_Neron ∧
      Tate_cyclotomic_inertia_formula ∧
      inertia_at_29_trivial_mod13_full :=
  h

/-- The proved numerical input consumed by the continued boundary.

The hypotheses are explicit.  The conclusion contains the displayed
discriminant, its `29`-adic valuation and divisibility, and the elementary
`928`/`32` arithmetic.  It does not claim Tate uniformization, Kodaira type,
a Néron conductor, a residual representation, or unramifiedness. -/
theorem tate_closure_continued_numerical_surface {A B : ℕ}
    (hsol : A ^ 4 + B ^ 4 = (B + 3) ^ 13)
    (hBpos : 1 ≤ B)
    (hA : ¬ 29 ∣ A) (hB : ¬ 29 ∣ B) (hC : 29 ∣ B + 3) :
    (freyWeierstrass A B).Δ =
        (16 : ℤ) * (A : ℤ) ^ 8 * (B : ℤ) ^ 8 *
          ((A : ℤ) ^ 4 + (B : ℤ) ^ 4) ^ 2 ∧
      Padic.valuation (freyDisc_in_Qp29 A B) =
        26 * (padicValNat 29 (B + 3) : ℤ) ∧
      (13 : ℤ) ∣ Padic.valuation (freyDisc_in_Qp29 A B) ∧
      (928 : ℕ) / 29 = 32 ∧
      (32 : ℕ) * 29 = 928 ∧
      (928 : ℕ) ≠ 32 ∧
      ¬ (29 : ℕ) ∣ 32 := by
  refine ⟨frey_discriminant_formula A B,
    valuation_discriminant_at_29 hsol hBpos hA hB,
    thirteen_dvd_valuation_discriminant_at_29 hsol hBpos hA hB hC,
    nine_twenty_eight_div_twenty_nine_numerical,
    thirty_two_mul_twenty_nine_numerical, ?_, ?_⟩
  · norm_num
  · norm_num

#check TateMultiplicativeQuotient
#check FullTateJSeries
#check TateUniformizationData
#check full_tate_j_series_with_remainder
#check uniformization_certificate_exact_j_equalities
#check TateClosureContinued
#check tate_closure_continued_forward
#check tate_closure_continued_numerical_surface

#print axioms full_tate_j_series_with_remainder
#print axioms uniformization_certificate_exact_j_equalities
#print axioms tate_closure_continued_forward
#print axioms tate_closure_continued_numerical_surface

end BealMatveevBeal.TateCurve