/-
  ArakelovRH/DesertBrothers/JitterInterface

  Minimal Lean 4.12 compatibility interface for the 1419 desert-brothers data.
  It deliberately avoids the upstream Mathlib 4.15 π-irrationality import and
  the large native_decide popcount proof that exceeds the Lean 4.12 CI budget.

  The fixed-point distance and list convention mirror
  DavidFox998/brothers-desert-proof. No theorem connecting this arithmetic
  data to modular old/new geometry is asserted here.
-/
import Mathlib.Data.Nat.GCD.Basic

namespace Beal.ArakelovRH.DesertBrothers

/-- Numerator of the fixed-point α₀ approximation exported by the upstream
    `Family.DirichletJitterTime` module. -/
def alpha0Numerator : ℕ := 3141592653

/-- Denominator of the fixed-point α₀ approximation exported upstream. -/
def alpha0Denominator : ℕ := 10000000000

/-- The residue of `p * α₀` in the upstream fixed-point model. -/
def fractionalResidue (p : ℕ) : ℕ :=
  (p * alpha0Numerator) % alpha0Denominator

/-- Scaled distance of `p * α₀` to the nearer integer in the fixed-point model.

    Dividing this number by `alpha0Denominator` gives the corresponding
    rational distance. The minimum is computed symbolically; no exhaustive
    `native_decide` certificate is run in this interface. -/
def scaledNearestIntegerDistance (p : ℕ) : ℕ :=
  let residue := fractionalResidue p
  min residue (alpha0Denominator - residue)

/-- The 35 desert-brothers values mirrored as data from the upstream Eutheos
    object. No popcount or exhaustive-search proof is recomputed here. -/
def brothers1419 : List ℕ :=
  [1419, 1841, 1907, 2113, 2411, 2777, 3251, 3467, 3671, 4091,
   4273, 4639, 5059, 5347, 5639, 5779, 6197, 6427, 6823, 7043,
   7583, 8321, 8999, 9413, 9859, 10259, 11311, 12433, 13513,
   14929, 17183, 19193, 23281, 44041, 52481]

/-- Small checked metadata about the vendored list. These equalities reduce
    directly; unlike the upstream popcount certificate they need no native
    code generation. -/
theorem brothers1419_anchor : 1419 ∈ brothers1419 := by
  simp [brothers1419]

theorem brothers1419_count : brothers1419.length = 35 := by
  rfl

/-- Data carrier for one Eutheos fixed-point jitter witness.

    The natural-number inequality is the denominator-cleared form of
    `scaledDistance / alpha0Denominator < 1 / p`. It is stored as data rather
    than generated by a large decision procedure. -/
structure EutheosJitter (p : ℕ) where
  p_pos : 0 < p
  jitter_lt_reciprocal :
    p * scaledNearestIntegerDistance p < alpha0Denominator

#check scaledNearestIntegerDistance
#check brothers1419_anchor
#check brothers1419_count
#print axioms EutheosJitter

end Beal.ArakelovRH.DesertBrothers