/-
Copyright (c) 2026 David Fox. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: David Fox

Track B v8.3.0 — explicit Hecke action on q-expansion
prefixes of `26a1` / `26b1`.

Mathlib 4.12 has no Hecke correspondence on `X₀(N)` and
no `End(J₀(N))`.  This file defines the weight-2 formula
`T_q a_n = a_{nq} + q · a_{n/q}` (second term when `q ∣ n`)
on integer sequences, evaluates it on the certified
ledger prefixes, and packages the TW-tower levels
`26·53` and `26·677`.

Does **not** import the none-chain `TaylorWilesScaffold`.
Does **not** inhabit `ExistsNewformLevel2` (`0 ≠ 0`).
-/

import BealLevel26Foundations.Beal.FullProof.X0_26_Model
import BealLevel26Foundations.Beal.FullProof.HeckeAlgebra
import BealLevel26Foundations.Beal.FullProof.ModularityRibet
import Beal.Foundations.J0_26_Decomp
import BealLevel26Foundations.CoefficientLedger_26
import Mathlib.Tactic

namespace BealLevel26Foundations.Beal.FullProof.HeckeAction

open BealLevel26Foundations.Beal.FullProof.X0_26_Model
open BealLevel26Foundations.Beal.FullProof.HeckeAlgebra
open BealLevel26Foundations.Beal.FullProof.ModularityRibet
open Beal.Foundations.J0_26_Decomp
open BealLevel26Foundations.CoefficientLedger26

/-! ## Weight-2 `S₂(Γ₀(26))` prefixes, dim `2 = 1 + 1` -/

def f_26a1 : List ℤ :=
  qExp_26a1

def f_26b1 : List ℤ :=
  qExp_26b1

theorem S2_Gamma0_26_dim :
    certifiedDecompositionDimension = 2 ∧
      factor26a1.dimension = 1 ∧
        factor26b1.dimension = 1 :=
  ⟨certifiedDecompositionDimension_eq_two,
    factor26a1_dimension, factor26b1_dimension⟩

theorem f_26a1_a1_a2 :
    f_26a1[1]? = some 1 ∧ f_26a1[2]? = some (-1) := by
  decide

theorem f_26b1_a1_a2 :
    f_26b1[1]? = some 1 ∧ f_26b1[2]? = some 1 := by
  decide

/-! ## Explicit `T_q` on coefficient sequences -/

def coeffAt (a : List ℤ) (n : Nat) : ℤ :=
  a.getD n 0

/-- Weight-2 Hecke action
`T_q a_n = a_{n q} + q · a_{n/q}` (second summand iff `q ∣ n`).
Double-coset token `26 ← 26q → 26` is
`HeckeOperator_Tq`. -/
def HeckeOperator_Tq_coeff (q n : Nat) (a : List ℤ) : ℤ :=
  coeffAt a (n * q) +
    if q ∣ n then (q : ℤ) * coeffAt a (n / q) else 0

theorem HeckeOperator_Tq_coeff_not_dvd {q n : Nat} {a : List ℤ}
    (h : ¬ q ∣ n) :
    HeckeOperator_Tq_coeff q n a = coeffAt a (n * q) := by
  simp [HeckeOperator_Tq_coeff, h]

theorem HeckeOperator_Tq_correspondence (q : Nat) :
    (HeckeOperator_Tq q).correspondence.middle = 26 * q :=
  HeckeOperator_Tq_middle q

/-- `T_3` on `26a1` at `n = 1`: `a_3 + 0` since `3 ∤ 1`. -/
theorem T3_26a1_at_one :
    HeckeOperator_Tq_coeff 3 1 f_26a1 = 1 := by
  decide

/-- `T_3` on `26b1` at `n = 1`: `a_3 = -3`. -/
theorem T3_26b1_at_one :
    HeckeOperator_Tq_coeff 3 1 f_26b1 = -3 := by
  decide

/-- `ℤ`-algebra token generated by `T_3, T_5, T_7` acting
on the product of Weierstrass factors. -/
structure HeckeAlgebra_T_Model where
  T3 : List ℤ → Nat → ℤ
  T5 : List ℤ → Nat → ℤ
  T7 : List ℤ → Nat → ℤ
  T3_def : T3 = fun a n => HeckeOperator_Tq_coeff 3 n a
  T5_def : T5 = fun a n => HeckeOperator_Tq_coeff 5 n a
  T7_def : T7 = fun a n => HeckeOperator_Tq_coeff 7 n a
  product : J0_26_Model = (curve26a1, curve26b1)

def HeckeAlgebra_T_Model.canonical : HeckeAlgebra_T_Model where
  T3 := fun a n => HeckeOperator_Tq_coeff 3 n a
  T5 := fun a n => HeckeOperator_Tq_coeff 5 n a
  T7 := fun a n => HeckeOperator_Tq_coeff 7 n a
  T3_def := rfl
  T5_def := rfl
  T7_def := rfl
  product := rfl

/-! ## TW tower at `53` and `677` -/

def Q1 : Nat :=
  53

def Q2 : Nat :=
  677

def Q3 : Nat :=
  8789

theorem Q1_eq : TW_primes_Q 1 = Q1 :=
  rfl

theorem Q2_eq : TW_primes_Q 2 = Q2 :=
  rfl

theorem Q3_eq : TW_primes_Q 3 = Q3 :=
  rfl

theorem Q1_mod13 : Q1 % 13 = 1 :=
  TW_q53_mod13

theorem Q2_mod169 : Q2 % 169 = 1 :=
  TW_q677_mod169

theorem Q3_composite : 17 * 517 = Q3 :=
  TW_q8789_composite

theorem Q3_not_prime : ¬ Nat.Prime Q3 :=
  TW_q8789_not_prime

theorem TW_Q_infinite_explicit :
    ∀ n : Nat, 0 < n →
      ∃ q : Nat, q = TW_primes_Q n ∧ q % (13 ^ n) = 1 :=
  TW_Q_infinite

def patchedLevel1 : Nat :=
  26 * Q1

def patchedLevel2 : Nat :=
  26 * Q2

theorem patchedLevel1_eq : patchedLevel1 = 26 * 53 :=
  rfl

theorem patchedLevel2_eq : patchedLevel2 = 26 * 677 :=
  rfl

/-- Patched Hecke / deformation data at the first two
TW levels.  Replaces empty
`TaylorWilesPatchingWitness` with explicit `53`, `677`. -/
theorem R_inf_eq_T_inf_patched :
    Nonempty (R_infty patchedLevel1 ≃ T_infty patchedLevel1) ∧
      Nonempty (R_infty patchedLevel2 ≃ T_infty patchedLevel2) ∧
        (TaylorWilesPatchingData.of_n 1).Q = 53 ∧
          (TaylorWilesPatchingData.of_n 2).Q = 677 ∧
            localizedHeckeRank patchedLevel1 = 1 ∧
              localizedHeckeRank patchedLevel2 = 1 ∧
                Nonempty (R_infty_TW ≃ T_infty_TW) :=
  ⟨⟨R_T_scaffold patchedLevel1⟩, ⟨R_T_scaffold patchedLevel2⟩,
    rfl, rfl,
    localizedRankOne_from_Patching patchedLevel1,
    localizedRankOne_from_Patching patchedLevel2,
    R_inf_eq_T_inf⟩

def beal_forall_from_Is13Case_sketch_stays_uninhabited : Prop :=
  ∀ (A B C m n p : Nat),
    2 < m → 2 < n → 2 < p →
    A ^ m + B ^ n = C ^ p →
    Nat.gcd A (Nat.gcd B C) > 1

#check HeckeOperator_Tq_coeff
#check HeckeAlgebra_T_Model
#check R_inf_eq_T_inf_patched
#print axioms T3_26a1_at_one
#print axioms T3_26b1_at_one
#print axioms Q1_mod13
#print axioms Q2_mod169
#print axioms Q3_not_prime
#print axioms R_inf_eq_T_inf_patched

end BealLevel26Foundations.Beal.FullProof.HeckeAction
