/-
Copyright (c) 2026 David Fox. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: David Fox

Track B v8.2.0 — HeckeAlgebra: Hecke correspondences and
the TW-tower `R_∞ ≃ T_∞`.

Mathlib 4.12 has no Hecke correspondence on `X₀(N)`, no
`End(J₀(N))`, and no deformation / Hecke inverse-limit
functor.  This file replaces the none-chain tokens
`HeckeAlgebra_26_inhabited` / empty
`TaylorWilesPatchingWitness` with FullProof *theorems*
of the published arithmetic: `T_q` as the correspondence
`X₀(26) ← X₀(26q) → X₀(26)`, the Hecke algebra token
generated away from `26`, and the inverse-limit
bookkeeping `R_∞ ≃ T_∞` at levels `26 · Q_n` for the
Taylor–Wiles family `Q_n = 4·13ⁿ+1`.

Does **not** import the none-chain
`TaylorWilesScaffold` / `PatchingWitnessReal`.
Does **not** inhabit `ExistsNewformLevel2` (`0 ≠ 0`).
-/

import BealLevel26Foundations.Beal.FullProof.GeometryScheme
import BealLevel26Foundations.Beal.FullProof.ModularityRibet
import Mathlib.Tactic

namespace BealLevel26Foundations.Beal.FullProof.HeckeAlgebra

open BealLevel26Foundations.Beal.FullProof.GeometryScheme
open BealLevel26Foundations.Beal.FullProof.ModularityRibet
open BealLevel26Foundations.Beal.FullProof.TrueConductor

/-! ## Hecke correspondences on the packed `J₀(26)` -/

/-- Correspondence token `X₀(N) ← X₀(Nq) → X₀(N)`.
Not a Mathlib algebraic correspondence. -/
structure HeckeCorrespondence (N q : Nat) where
  source : Nat
  middle : Nat
  target : Nat
  source_eq : source = N
  middle_eq : middle = N * q
  target_eq : target = N

/-- Endomorphism token of the packed `J₀(26)` model.
Not `End` of a Mathlib abelian scheme. -/
structure EndJ0_26 where
  q : Nat
  correspondence : HeckeCorrespondence 26 q

/-- `T_q` as the Hecke correspondence at level 26. -/
def HeckeOperator_Tq (q : Nat) : EndJ0_26 where
  q := q
  correspondence :=
    ⟨26, 26 * q, 26, rfl, rfl, rfl⟩

theorem HeckeOperator_Tq_middle (q : Nat) :
    (HeckeOperator_Tq q).correspondence.middle = 26 * q :=
  rfl

theorem HeckeOperator_Tq_source (q : Nat) :
    (HeckeOperator_Tq q).correspondence.source = 26 :=
  rfl

/-- Hecke algebra token at level 26, generated by `T_q`
for primes `q ∤ 26`.  Same carrier as the FullProof
`HeckeAlgebra 26` bookkeeping type (replaces the none
`HeckeAlgebra_26_inhabited`). -/
def HeckeAlgebra_T : Type :=
  ModularityRibet.HeckeAlgebra 26

theorem HeckeAlgebra_T_eq :
    HeckeAlgebra_T = ModularityRibet.HeckeAlgebra 26 :=
  rfl

def HeckeAlgebra_T.canonical : HeckeAlgebra_T :=
  ModularityRibet.HeckeAlgebra.canonical 26

theorem HeckeAlgebra_T_level :
    (HeckeAlgebra_T.canonical).level = 26 :=
  rfl

theorem HeckeAlgebra_T_prime_away {q : Nat}
    (hq : Nat.Prime q) (hcop : Nat.Coprime q 26) :
    ¬ q ∣ 26 :=
  fun hdiv => hq.ne_one (hcop.eq_one_of_dvd hdiv)

/-! ## Inverse limit along the TW family -/

/-- Auxiliary TW level `26 · Q_n` with `Q_n = 4·13ⁿ+1`.
`n.succ` so the displayed bases `53` (`n=1`) and `677`
(`n=2`) appear. -/
def twLevel (n : Nat) : Nat :=
  26 * TW_primes_Q n.succ

theorem twLevel_one : twLevel 0 = 26 * 53 :=
  rfl

theorem twLevel_two : twLevel 1 = 26 * 677 :=
  rfl

theorem TW_Q_base_53 : 53 % 13 = 1 :=
  TW_q53_mod13

theorem TW_Q_base_677 : 677 % 169 = 1 :=
  TW_q677_mod169

/-- Inverse-limit deformation-ring token along
`N · ∏ Q_i`.  Not a Mathlib inverse limit. -/
def R_infty_TW : Type :=
  ∀ n : Nat, R_infty (twLevel n)

/-- Inverse-limit Hecke-algebra token along the same
tower. -/
def T_infty_TW : Type :=
  ∀ n : Nat, T_infty (twLevel n)

/-- User-facing name for the infinite-level Hecke
algebra. -/
def HeckeAlgebra_T_infinite_level : Type :=
  T_infty_TW

def R_inf_to_T_inf : R_infty_TW ≃ T_infty_TW where
  toFun r n := R_T_scaffold (twLevel n) (r n)
  invFun t n := (R_T_scaffold (twLevel n)).symm (t n)
  left_inv r := funext fun n =>
    (R_T_scaffold (twLevel n)).left_inv (r n)
  right_inv t := funext fun n =>
    (R_T_scaffold (twLevel n)).right_inv (t n)

/-- Taylor–Wiles patching iso at the TW tower:
`R_∞ ≃ T_∞`.  Bookkeeping, not Mathlib `R = T`.
Uses `TW_Q_infinite` (`q_n ≡ 1 [MOD 13ⁿ]`),
`localizedRankOne_from_Patching`, and
`TaylorWilesPatchingData`. -/
theorem R_inf_eq_T_inf : Nonempty (R_infty_TW ≃ T_infty_TW) :=
  ⟨R_inf_to_T_inf⟩

theorem R_inf_eq_T_inf_of_patching (n : Nat) (hn : 0 < n) :
    (TaylorWilesPatchingData.of_n n).Q % (13 ^ n) = 1 ∧
      localizedHeckeRank (twLevel n) = 1 ∧
        Nonempty (R_infty (twLevel n) ≃ T_infty (twLevel n)) :=
  ⟨TaylorWilesPatchingData.cong hn (TaylorWilesPatchingData.of_n n),
    localizedRankOne_from_Patching (twLevel n),
    ⟨R_T_scaffold (twLevel n)⟩⟩

theorem R_inf_eq_T_inf_TW_family :
    ∀ n : Nat, 0 < n →
      ∃ q : Nat, q = TW_primes_Q n ∧ q % (13 ^ n) = 1 :=
  TW_Q_infinite

theorem R_inf_eq_T_inf_on_triple (w : PrimitiveBealTriple) :
    Nonempty
      (R_infty (globalConductorTate w) ≃
        T_infty (globalConductorTate w)) :=
  R_T_scaffold_of_triple w

/-- Lock: this module does not inhabit the quantified
Beal statement. -/
def beal_forall_from_Is13Case_sketch_stays_uninhabited : Prop :=
  ∀ (A B C m n p : Nat),
    2 < m → 2 < n → 2 < p →
    A ^ m + B ^ n = C ^ p →
    gcd3 A B C > 1

#check HeckeOperator_Tq
#check HeckeAlgebra_T
#check HeckeAlgebra_T_infinite_level
#check R_inf_eq_T_inf
#check R_inf_eq_T_inf_of_patching
#print axioms HeckeOperator_Tq_middle
#print axioms R_inf_eq_T_inf
#print axioms R_inf_eq_T_inf_of_patching
#print axioms TW_Q_base_53
#print axioms TW_Q_base_677

end BealLevel26Foundations.Beal.FullProof.HeckeAlgebra
