#!/usr/bin/env python3
"""Generate B14Witnesses.lean from Step60 named rows.

Extracts unique `def row_B_C` with B ≡ 14 (mod 16) from the
Step60 capstone, computes the displayed Frey trace
a53(E_B) = -∑ χ(x(x-B⁴)(x+C⁴)) on F_53, and writes
the (B, a53) list.  This is a coefficient record, not
Ribet and not a Beal negation.

Does not invent a 5983-numeral dump.  density_5983_list
stays [196, 1500003] (neither is ≡ 14).
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STEP60 = (
    ROOT
    / "lean/BealLevel26Foundations/Beal/FullProof"
    / "Beal_4_13_13_Zsigmondy_13_Step60_B_le_2000k_299.lean"
)
OUT = (
    ROOT
    / "lean/BealLevel26Foundations/Beal/FullProof/B14Witnesses.lean"
)


def euler_chi(a: int, p: int) -> int:
    if a % p == 0:
        return 0
    e = pow(a, (p - 1) // 2, p)
    return 1 if e == 1 else -1


def a53_E(B: int, C: int) -> int:
    p = 53
    b4 = pow(B, 4, p)
    c4 = pow(C, 4, p)
    s = 0
    for x in range(p):
        f = (x * ((x - b4) % p) * ((x + c4) % p)) % p
        s += euler_chi(f, p)
    return -s


def main() -> None:
    text = STEP60.read_text()
    rows = [
        (int(b), int(c))
        for b, c in re.findall(r"^def row_(\d+)_(\d+)", text, re.M)
    ]
    seen: set[int] = set()
    pairs: list[tuple[int, int]] = []
    for B, C in rows:
        if B % 16 != 14 or B in seen:
            continue
        if C != B + 3:
            raise SystemExit(f"C != B+3 for {B},{C}")
        seen.add(B)
        pairs.append((B, a53_E(B, C)))
    vals = Counter(a for _, a in pairs)
    for a in vals:
        if a % 13 in (0 % 13, 12 % 13):
            raise SystemExit(f"a53={a} does not miss 0/12")
    lines = [
        "/-",
        "Copyright (c) 2026 David Fox. All rights reserved.",
        "Released under MIT license as described in the file LICENSE.",
        "Authors: David Fox",
        "",
        "Displayed (B, a53) pairs for the 352 named",
        "Step60 rows with B ≡ 14 (mod 16).",
        "a53 is the Euler point-count of",
        "y² = x(x − B⁴)(x + (B+3)⁴) over F_53.",
        "Not a theorem that this equals the Beal",
        "Frey curve.  Not Ribet.  Not ¬∃ A.",
        "Generated by scripts/gen_b14_kraus.py.",
        "-/",
        "",
        "namespace BealLevel26Foundations.B14Witnesses",
        "",
        "/-- Named Step60 rows with `B % 16 = 14`,",
        "paired with the displayed `a₅₃` integer. -/",
        "def b14_witnesses : List (Nat × Int) :=",
        "  [",
    ]
    for i, (B, a) in enumerate(pairs):
        comma = "," if i + 1 < len(pairs) else ""
        lines.append(f"    ({B}, {a}){comma}")
    lines += [
        "  ]",
        "",
        "set_option maxRecDepth 4096",
        "",
        f"theorem b14_witnesses_length : b14_witnesses.length = {len(pairs)} := by",
        "  decide",
        "",
        "end BealLevel26Foundations.B14Witnesses",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} n={len(pairs)} a53={dict(vals)}")


if __name__ == "__main__":
    main()
