/-
  Galois/07n_NormalizedEigenlineQExpansion

  A V-specific q-expansion argument for a normalized one-dimensional
  eigenline.  This is the small coefficient argument needed at a Ribet
  descent edge: the coefficient at q detects the first summand, while the
  coefficients at q^(p*n) detect the second.

  The authentic 11,774-byte Batch148 source records that its intended
  weight-two eigenform is normalized by a_1 = 1.  It does not construct that
  form or prove the normalization in Lean.  Accordingly, the normalized
  eigenline below is explicit proof data; no Batch148 `True` placeholder is
  imported as evidence.

  Diamond--Shurman Proposition 8.3.2 concerns Frobenius on Pic^0 after good
  reduction.  It belongs to Batch148's trace ledger and is not used as a
  q-expansion or Ihara theorem here.
-/
import Beal.Galois.«07g_IharaOnV»

namespace Beal.Galois

/-- Proof-relevant data saying that `V` is generated by a form normalized at
    its first q-expansion coefficient.

    This is deliberately stronger than the current finite "genuine form"
    predicate: it records the exact one-dimensional eigenline property used
    by the coefficient argument. -/
structure NormalizedEigenlineData
    (ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ)) where
  generator : CoefficientSequence ℓ
  generator_mem : generator ∈ V
  spans :
    ∀ f : CoefficientSequence ℓ, f ∈ V →
      ∃ c : ZMod ℓ, c • generator = f
  coefficient_one : generator 1 = 1

/-- On a normalized eigenline, the first coefficient detects the zero form. -/
theorem NormalizedEigenlineData.eq_zero_of_coefficient_one_eq_zero
    {ℓ : ℕ}
    {V : Submodule (ZMod ℓ) (CoefficientSequence ℓ)}
    (D : NormalizedEigenlineData ℓ V)
    {f : CoefficientSequence ℓ}
    (hf : f ∈ V)
    (hfOne : f 1 = 0) :
    f = 0 := by
  rcases D.spans f hf with ⟨c, hc⟩
  have hcZero : c = 0 := by
    have hAtOne := congrFun hc 1
    simpa [D.coefficient_one, hfOne] using hAtOne
  calc
    f = c • D.generator := hc.symm
    _ = 0 := by simp [hcZero]

/-- The normalized-eigenline q-expansion argument supplies the exact
    coefficient cancellation proposition required by 07g.

    The proof uses only two elementary facts about the two degeneracy
    expansions:

    * because `p` is prime, the `q^1` coefficient of `Bp p ℓ b` is zero;
    * the `q^(p*n)` coefficient of `Bp p ℓ b` is the `q^n` coefficient of
      `b`.

    Thus no full analytic Fourier theory, modular-curve Jacobian, or
    Frobenius/Hecke placeholder is smuggled into the result. -/
theorem QExpansionPrincipleOnV_fromEigenline
    (M p ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ))
    (hp : p.Prime)
    (D : NormalizedEigenlineData ℓ V) :
    QExpansionPrincipleOnV M p ℓ V := by
  intro _hV a b ha _hb hRelation
  have hpNotDvdOne : ¬ p ∣ 1 := by
    simpa using hp.ne_one
  have haOne : a 1 = 0 := by
    have hAtOne := congrFun hRelation 1
    simpa [Bp, BpCoeff, hpNotDvdOne] using hAtOne
  have haZero : a = 0 :=
    D.eq_zero_of_coefficient_one_eq_zero ha haOne
  have hBpZero : Bp p ℓ b = 0 := by
    simpa [haZero] using hRelation
  have hbZero : b = 0 := by
    funext n
    have hAtPN := congrFun hBpZero (p * n)
    have hpDvd : p ∣ p * n := dvd_mul_right p n
    simpa [Bp, BpCoeff, hpDvd, hp.ne_zero] using hAtPN
  exact ⟨haZero, hbZero⟩

/-- The same normalized eigenline data closes the restricted 07g Ihara
    conclusion on the exact descent edge. -/
theorem IharaKernelZeroOnV_FromNormalizedEigenline
    (M p ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ))
    (hp : p.Prime)
    (hV : IsGenuineFormSubmoduleAtLevel M ℓ V)
    (D : NormalizedEigenlineData ℓ V) :
    IharaKernelZeroOnV M p ℓ V :=
  ihara_zero_on_genuine_V_conditional M p ℓ V hV
    (QExpansionPrincipleOnV_fromEigenline M p ℓ V hp D)

#print axioms NormalizedEigenlineData
#print axioms NormalizedEigenlineData.eq_zero_of_coefficient_one_eq_zero
#print axioms QExpansionPrincipleOnV_fromEigenline
#print axioms IharaKernelZeroOnV_FromNormalizedEigenline
-- Expected foundational dependencies: [propext, Quot.sound] only.

end Beal.Galois

namespace Beal.QExpansionSupplier

/-- Public v7.1.0 name for the normalized-eigenline supplier. -/
theorem QExpansionPrincipleOnV_fromEigenline
    (M p ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (Beal.Galois.CoefficientSequence ℓ))
    (hp : p.Prime)
    (D : Beal.Galois.NormalizedEigenlineData ℓ V) :
    Beal.Galois.QExpansionPrincipleOnV M p ℓ V :=
  Beal.Galois.QExpansionPrincipleOnV_fromEigenline M p ℓ V hp D

#print axioms QExpansionPrincipleOnV_fromEigenline

end Beal.QExpansionSupplier